FROM node:18.16.1 as base
WORKDIR /home
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

COPY .npmrc ./pnpm-lock.yaml ./package.json ./pnpm-workspace.yaml /home/app/
COPY ./dist ./services/backend/package.json /home/app/services/backend/
RUN curl -fsSL https://get.pnpm.io/install.sh | bash -
RUN cd /home/app/services/backend/ && pnpm install --prod
CMD cd /home/app/services/backend/ && pnpm start:prod
EXPOSE 3000
